quiz_project/urls.py
from django.contrib import admin
from django.urls import path
from auapp.views import user_login, user_signup, user_logout, user_np, about_me
from quizapp.views import home, takequiz, deletequiz, submitquiz, newquiz, newquestion, results, report, aboutme
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    # Login App
    path('admin/', admin.site.urls),
    path("user_login/", user_login, name="user_login"),
    path("user_signup/", user_signup, name="user_signup"),
    path("user_logout/", user_logout, name="user_logout"),
    path("user_np/", user_np, name="user_np"),
    path("about_me/", about_me, name="about_me"),

    # Main Project
    path("", home, name="home"),
    path("deletequiz/<quiz_id>", deletequiz, name="deletequiz"),
    path("takequiz/<quiz_id>", takequiz, name="takequiz"),
    path("takequiz/<quiz_id>/submit", submitquiz, name="submitquiz"),
    path("newquiz/", newquiz, name="newquiz"),
    path("newquiz/<quiz_id>/newquestion", newquestion, name="newquestion"),
    path("results/", results, name="results"),
    path("results/<quiz_id>/report", report, name="report"),
    path("aboutme/", aboutme, name="aboutme"),
]

urlpatterns += staticfiles_urlpatterns()

quizapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer_text = models.CharField(max_length=100)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return self.answer_text


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    question_text = models.CharField(max_length=100, null=True)
    mark = models.PositiveIntegerField(null=True)
    answers = models.ManyToManyField(Answer)

    def __str__(self):
        return self.question_text


class Quizzes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    questions = models.ManyToManyField(Question)

    def __str__(self):
        return self.title


class Attempt(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    quiz = models.ForeignKey(Quizzes, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    score = models.PositiveIntegerField(null=True)

    def __str__(self):
        return self.quiz.user.username + ' - ' + self.answer.answer_text

templates/quiz/aboutme.html
{% extends 'base.html' %}
{% block title %} Contact Us {% endblock %}

{%block content %}
<div class="jumbotron text-center">
    <h1 class="display-3"><strong>Greetings!</strong>
    <p class="lead"><h3>Thank You for visiting my website</h3></p>
    <br>
    <h5> I am a third year CSE student graduating in 2023 </h5>
    <p>
    </p>
  </div>

{% endblock %}

templates/quiz/home.html
{% extends 'base.html' %}
{% block title %} Home Page {% endblock %}

{%block content %}

<h3 class="title is-3 center-align">Available Quizzes</h3>
<div class="section">

    {% for q in quiz %}
	    <h4>{{ q.title }}</h4>
        <a class="btn-2 pull-left btn waves-effect waves-light " href="{% url 'deletequiz' q.id %}" style="float: right; margin-right: 100px; margin-left: 20px;">Delete Quiz</a> 
        <a class="btn-2 pull-left btn waves-effect waves-light " href="{% url 'takequiz' q.id %}" style="float: right; margin-right: 30px;">Take Quiz</a>
        
        <h6>{{ q.description }}</h6>
        <br>
	    <div class="divider"></div>
    {% endfor %}
    
</div>

{% endblock %}

templates/quiz/newquestion.html
{% extends 'base.html' %}
{% block title %} New Question {% endblock %}

{%block content %}
<div class="row center-align">
    <div class="col s12">

    <form method="post" enctype="multipart/form-data" action="" role="form">
    {% csrf_token %}

    <h3 class="title is-3">Create a new question</h3>

    <div class="input-field col s12">
      {{ form.question_text }}
      <label for="question_text">Question ?</label>
    </div>
  
    <div class="input-field col s12">
      {{ form.marks }}
      <label for="marks">Marks</label>
    </div>
  
    <div class="input-field col s9">
      <input type="text" name="answer_text" id="id_answer_text" class="validate" required>
      <label for="answer_text">Option 1</label>
    </div>
  
    <div class="input-field col s3">
      <select id="id_is_correct" name="is_correct" required>
        <option value="" disabled selected>Choose yes or no</option>
        <option value="True">Yes</option>
        <option value="False">No</option>
      </select>
      <label>Is this the correct answer ?</label>
    </div>
  
    <div class="input-field col s9">
      <input type="text" name="answer_text" id="id_answer_text" class="validate" required>
      <label for="answer_text">Option 2</label>
    </div>
  
    <div class="input-field col s3">
      <select id="id_is_correct" name="is_correct" required>
        <option value="" disabled selected>Choose yes or no</option>
        <option value="True">Yes</option>
        <option value="False">No</option>
      </select>
      <label>Is this the correct answer ?</label>
    </div>
  
    <div class="input-field col s9">
      <input type="text" name="answer_text" id="id_answer_text" class="validate" required>
      <label for="answer_text">Option 3</label>
    </div>
  
    <div class="input-field col s3">
      <select id="id_is_correct" name="is_correct" required>
        <option value="" disabled selected>Choose yes or no</option>
        <option value="True">Yes</option>
        <option value="False">No</option>
      </select>
      <label>Is this the correct answer ?</label>
    </div>
  
    <div class="input-field col s9">
      <input type="text" name="answer_text" id="id_answer_text" class="validate" required>
      <label for="answer_text">Option 4</label>
    </div>
  
    <div class="input-field col s3">
      <select id="id_is_correct" name="is_correct" required>
        <option value="" disabled selected>Choose yes or no</option>
        <option value="True">Yes</option>
        <option value="False">No</option>
      </select>
      <label>Is this the correct answer ?</label>
    </div>

    <div class="col s12">
      <p class="control">
        <button type="submit" value="login" class="btn waves-effect waves-light backcl">
          Add Question
        </button>
      </p>
    </div>
  
    <div class="col s12">
      <a class="btn waves-effect waves-light backcl" href="{% url 'home' %}">Go to Home</a>      
    </div>
  
    </form>
    </div>
  </div>

{% endblock %}

templates/quiz/newquiz.html
{% extends 'base.html' %}
{% block title %} New Quiz {% endblock %}

{%block content %}

<div class="row center-align">
    <div class="col s12">

      <form method="post" enctype="multipart/form-data" action="" role="form">
        {% csrf_token %}
        
        <h3 class="title is-3">Create a new Quiz</h3>

        <div class="input-field col s12">
            {{ form.title }}
            <label for="description">Title</label>
        </div>

        <div class="input-field col s12">
          {{ form.description }}
          <label for="description">Description</label>
        </div>

        <div class="field">
          <p class="control">
            <button style="margin-top:50px;" type="submit" value="login" class="btn backcl waves-effect waves-light">
              Create new Quiz
            </button>
          </p>
        </div>

      </form>
    </div>
  </div>

{% endblock %}

templates/quiz/report.html
{% extends 'base.html' %}
{% block title %} Report {% endblock %}

{% block content %}
  <h3 class="title is-3 center-align">Answer Key</h3>
  <div class="section">
  	<h4>{{ quiz.title }}</h4>
  </div>

  <div class="col s12">
    <form class="col s12">
      {% csrf_token %}

      {% for question in quiz.questions.all %}
        <div class="col s12">
          <br>
          <p style="margin-left:130px;">{{ question.question_text }}</p>
          <input type="hidden" name="question" value="{{ question.id }}">
        </div>

      {% for answer in question.answers.all %}
        <div class="input col s12">
          <label style="margin-left:130px;">
            <input name="answer" type="checkbox" value="{{ answer.id }}" {% if answer.is_correct == True %}checked="checked"{% endif %}/>
            <span>{{ answer.answer_text }}</span>
          </label>          
        </div>
      {% endfor %}
      <br>
      <div class="divider"></div>
    {% endfor %}
    </form>
  </div>
  <center>
  <div class="col s12">
    <a class="btn waves-effect waves-light backcl" style="margin-top:30px; margin-bottom: 40px;" href="{% url 'home' %}">Go to Home</a>      
  </div>
  </center>
</div>

{% endblock %}

templates/quiz/results.html
{% extends 'base.html' %}
{% block title %} Results {% endblock %}

{% block content %}
    <h3 class="title is-3 center-align">Result</h3>
    <div class="section">

        {% for data in attempt %}
            <h4>{{ data.quiz.title }}</h4> 
            <a class="btn-2 pull-left btn waves-effect waves-light" href="{% url 'report' data.quiz.id %}" style="float: right;">Scored: {{ data.score }}</a>
            <h6>{{ data.quiz.description }}</h6>
            <br>    
            <div class="divider"></div>
        {% endfor %}
        
    </div>

{% endblock %}

templates/quiz/takequiz.html
{% extends 'base.html' %}
{% block title %} Take Quiz {% endblock %}

{%block content %}
  <div class="section">
  	<h4>{{ quiz.title }}</h4>
  </div>

  <div class="col s12" style="margin-left:130px;">
    <form method="post" id="sectionform" action="{% url 'submitquiz' quiz.id %}" role="form" class="col s12">
    {% csrf_token %}

      {% for question in quiz.questions.all %}
        <div class="col s12">
          <br>
          <p>{{ question.question_text }}</p>
          <input type="hidden" name="question" value="{{ question.id }}">
        </div>

      {% for answer in question.answers.all %}
        <div class="input col s12">
          <label>
            <input name="answer" type="checkbox" value="{{ answer.id }}">
            <span>{{ answer.answer_text }}</span>
          </label>
        </div>
      {% endfor %}
      <br><div class="divider"></div>
    {% endfor %}

    <div class="col s12">
      <center>
        <button type="submit" style="margin-top:40px; margin-bottom:40px" value="login" class="btn backcl waves-effect waves-light" onclick="return confirm('Submit your responses?')">
          Submit
        </button>
      </center>
    </div>
    </form>
  </div>
</div>
{% endblock %}